#+title: diary-2023-7-23
#+author: Peerin
#+date: <2023-07-23 日>

不知为何，突然萌生写日记的想法。可能是被同班某个张同学的行为鼓动，或是自初中写小说被抓之后写作的欲望再次萌生。
想到什么就写什么罢。反正我也不打算讲求什么格式了，文法了······
首先是，我并不是在写日记的当下才恰好文思泉涌，实际上，大多数我文思泉涌的时候我并没有动笔去记录，这让我感到很遗憾。很多当时很自我震撼的想法，随之便溜走了。我想通过写日记来让自己尽力回忆，然后尽可能多得记录。
再者呢，我并不害怕自己的日记被公开。实际上我是极其渺小的，就和其他几十亿人一样。大多数人的一辈子注定是默默无闻的，在历史中激不起什么波澜（尽管这并不一定有意义）。极端来说，就算你在公共场合自慰、拉屎，做一些极其吸引别人眼球的行为，你的事迹也不会流传多久。
你我都是无名之辈。无名之辈害怕自己的日记被曝光，这不就是杞人忧天吗？相反，我想尽力呐喊，让世界的人都听到我的声音，但是希望渺茫，所以，真正令我窒息的或许不是遗臭万年，而是“岁月无痕”。
写吧。其实字数多少无所谓。我在写给自己看，茫茫互联网，又有几个陌生人能够踏足这里？
想到什么写什么。
很早之前便想记录下来。人是多么自私的动物啊！这并非全是贬义。实际上，我认为我在陈述事实，客观中立的事实。自私作为人的一种本质，令人绝望又令人感动。
绝望的是，你肉眼可及与不可及的地方，人类都在玩着利益游戏。因为人是第一人称主观动物，始终活在自己的世界里，无法真正踏步他人的领土（思维，感受）分毫。所以，人总是以自我为中心。
都是在尽可能享受，这没有错，这是事实。肉欲间接带来精神愉悦，或者更直接的，直接得到精神愉悦。亲情是什么，一开始，人便把孩子当作自己快乐的玩具，是自己获得精神愉悦的媒介。
这没有错误，因为大部分人获得精神愉悦的方法表现出来是正向的，即温馨的父爱和母爱。
其他情感类似。所以这些情感本身不假，只不过我们要认识到，情感产生的根本来自人的私欲。
想到什么写什么。
恍恍惚惚，我又来到了学校，无法分清昨日今日明日。
想到什么写什么。
我总是止不住的内心低语，看了部分托利的《当下的力量》，感觉很有用，但是目前很多借口让我没有继续看下去，将其搁置在了一边。有时候低语让我撕裂，头痛，安静的时刻什么时候才能到来。我喜欢安静、温馨、舒适。
就到这里。

