#+title: 对时间的认识
#+author: Peerin
#+date: <2023-08-19 六 09:46>

* 源起

我还没有读完埃克哈特-托利的《当下的力量》，这是一本可能需要很长时间与实践才能真正读完的书，如果仅仅为了翻完而读完，你不仅需要

承受无法理解书中内容的茫然和痛苦，还将一无所获。

书中有讲到关于时间的认识问题，毕竟，这本书的标题就是 *当下的力量* 对于时间的探讨一定会占据不少的一部分。

* 当下

过去和未来都是幻象，都是想象，只有当下才是最真实的。 你的大脑或者说思维，产生了心理时间，它让你认为存在过去和未来，

然而，这只是它们创造的，是你的臆想，客观存在的只有当下，影响真实世界的只有当下。

因此要活在当下，避免无必要的对未来的焦虑和对过去的懊悔。他们都是幻觉。

判断自己是否处于当下的一种方法就是关注自己的内在并且向自己发问： *此刻我很自在吗？*

当一个人活在当下，不再认同心理时间之后，它的回答很显然， *是的* 。

我现在当然很自在，我没有去焦虑未来，没有懊悔过去。前者还意味着我没有以结果为导向而去做当下的事情，抛去过多的无意识的情绪之后，一定会很自在。

我在读这本书的时候，便想着要写这样一篇博文，那时候，我就是在憧憬未来，但我不确定这是否是滥用时间，对于时间的滥用只会导致无意识的思维小我接管本然的自己。

* 问题的产生

#+begin_quote
问题是思维创造的，它需要时间来生存。
#+end_quote

你在当下，你有什么问题呢？

*我还没有做这个、马上我就要做那个了、如果不做那个我会怎么怎么样......*

这些都是大脑对于未来的焦虑，对于未来的问题，当下是无法处理的，但不可否认使用钟表时间来估计和规划事务是一种运用当下的方式。

我现在也没有很理解，如果不思考未来，如何提前规划？毕竟有些事情只是交给未来的当下是不能很好的处理的。

但总之，理想的进入 *本我* 状态下的状态特征就是： 不是完全以结果为目的去做当下的事情，不去焦虑虚假的未来，不去懊悔不存在的过往，自在的感受当下的时刻，那么就会永远快乐。

痛苦在被觉察到的时候就会消失，黑暗不会在光明中生存，没有一个正常的人想要自己处于痛苦之中。

因此，痛苦也是一种幻觉。

体会当下，做当下的事情，合理运用钟表时间来估计和规划，不被心理时间所裹挟，进入本我，逐渐开悟。


