#+title: How Internet works?
#+author: Peerin
#+date: <2023-08-06 日 14:46>

* 文章起源
最近草草刚看完《网络是怎样连接的》，记下一文以便留下更深印象。

有些时候，说出来，写下来，讲出来，才知道自己是否是真的懂了。

* TCP/IP网络模型
1. 应用层
2. 传输层
3. 网络层
4. 数据链路层   
5. 物理层

** 应用层

HTTP 协议便是典型的应用层协议，此外还有SMTP、FTP、WebSocket等等吧。

** 传输层

我个人认为，对于程序员来说，理解 *传输层协议* 和 *网络层协议* 是学好程序员网络的关键。

1. TCP
2. UDP

*** TCP

TCP 很强大，通过一系列巧妙的方法，不仅提高了效率（相对于其他解决方案），同时保证了通信的完整。

_具体协议规范的内容我目前以后再补充在这里。_

*** UDP

UDP 很方便，但是远不如TCP强大，理解了TCP,UDP也就理解了。

** 网络层

1. IP(ipv4)
2. IPv6
3. ICMP
...

网络层很抽象，他既不是实际转发设备最底层需要的信息，也不像TCP一样有强大复杂的功能。

但是他的名字却很响亮，IP地址这个词无处不在。

** 网络链路层

1. 以太网协议
2. ARP
...

这一层很实际，就是转发设备最终寻找目标设备所要用的

** 物理层

_知识匮乏_

* 整体过程

以http应用为例（浏览器）

1. 浏览器构造http body和header部分(DNS域名解析省略)

2. 浏览器软件利用Socket,请求操作系统协议栈使用TCP协议将包发送出去

3. 协议栈请求网卡驱动程序调用网卡将包发送出去

4. 网卡根据目标IP地址，通过ARP找到下一个转发设备接口的MAC地址，并转化数字信号为电信号将包发送出去

...(中间可能经历很多家庭局域网的网络转发设备，如：集线器、交换机、路由器等)

5. 到达家庭路由器，家庭路由器判断目标IP不是本局域网内的，然后根据默认网关，找到默认网关的MAC地址，将包发送出去。这个默认网关一般是网络运营商的边界路由器

6. 网络包从路由器的端口出去，假如是FTTH接入网（光纤入户），则先经过一个转换设备（有多种），将电信号转化成光信号
   光信号到达另一端，转化成电信号，再交给路由器。

7. 进入互联网后，网络包不断的经过转发设备，其MAC头部或者其他头部被不断更换，但是目标IP地址始终不变
   各个路由器接收到网络包后，根据自身路由表进行接力，直到到达目标IP地址的网络设备

...(经过不同的网络运营商的不同路由器)

8. 终于，到达了某个网络运营商的路由器，它查表后发现，这个包的目标地址就在我的表内
   它找到目标的MAC地址，构造MAC头部并且把网络包从指定端口发出去。

9. 此时，要么直接到达目标服务器的网卡（服务器拥有公网地址），要么到达某个NAT路由器，无论如何，
   网络包都会最终到达目标设备。

10. 服务器操作系统接收到网卡的中断，协议栈请求网卡驱动设备获得网卡内存中的网络包内容，
    如果是TCP，则进行一系列检测来保证网络包完整到达。

11. 协议栈根据端口号等信息，确定本地的目标Socket,然后将网络包放到本地Socket的内存缓冲区中，并通知
    Socket来取包

12. Socket获得包之后交给应用程序（http情境下一般是Web服务器），此时的网络包只剩下了http协议部分（header和body），
    程序根据这些内容执行接下来的操作...

注意：这个过程省略很多内容，比如DNS域名服务器、CDN网络内容服务商、防火墙、NAT地址转换设备、以及可能存在的IPv4和IPv6转换设备等等，
不过，这些都是细节部分，总的路线是不变的。
   
